version: 0.0.{build}

max_jobs: 1
configuration: Release

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input


install:
  - ps: $version = (cat version.txt); Set-AppveyorBuildVariable 'nugetVersion' $version

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(nugetVersion)
  package_version: $(nugetVersion)
  assembly_version: $(nugetVersion)
  file_version: $(nugetVersion)
  informational_version: $(nugetVersion)

before_build:
  - nuget restore

build:
  parallel: true
  project: Snapper.sln
  publish_nuget: true

test: off

test_script:
  - ps: dotnet vstest (Get-ChildItem -Path "*/bin/*Tests.dll" -Recurse)

deploy:
  - provider: NuGet
    api_key:
      secure: YqF5spLEf4ATLwb/BhCXnRf/uLN1i2+Y3fgfZz2mN+bwSNMh52JGAR8FNkXe/Kmw
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

skip_commits:
  files:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - LICENSE
  - README.md
